image: alpine/latest
secrets:
  - 06907e6b-98a4-4c14-ac4e-f3561adf7b14
environment:
  - repo: giloliveira.net
  - host: giloliveira.net
  - user: srht
packages:
  - hugo
tasks:
  - build: |
    cd $repo
    hugo
  - deploy: |
    rsync -rtvzP $repo/public/ $user@$host:~/www/giloliveira.net
