image: archlinux
secrets:
  - 06907e6b-98a4-4c14-ac4e-f3561adf7b14
packages:
  - go
  - hugo
tasks:
  - build: |
      cd giloliveira.net
      hugo
  - deploy: |
      rsync -rtvzP giloliveira.net/public/ srht@giloliveira.net:~/www/giloliveira.net
